env = Environment()

env.Append(CPPFLAGS = ['-ggdb3', '-fPIC', '-Wall', '-g'])
env.Append(CPPPATH = ['../include', '/usr/include', '.'])
env.Append(LIBS = ['rt', 'pthread', 'log4cxx'])
env.Append(LIBPATH = ['/usr/lib64', '/usr/local/lib', '/usr/lib/nptl'])

env.SharedLibrary('nframe', [
	'NFTimer.cpp', 
	'NFThread.cpp', 
	'NFGlobal.cpp', 
	'NFMain.cpp', 
  'Log.cpp',
])